import { ObjectId } from 'mongoose';

export interface IUser {
  _id: ObjectId;
  githubId: string;
  username: string;
  name: string;
  email: string;
  avatar: string;
  bio: string;
  createdAt: Date;
  updatedAt: Date;
}

export type CodeSource = 'ai' | 'colleague' | 'personal' | 'other';

export interface IPost {
  _id: ObjectId;
  author: ObjectId | IUser;
  title: string;
  description: string;
  code: string;
  language: string;
  source: CodeSource;
  createdAt: Date;
  updatedAt: Date;
}

export interface IComment {
  _id: ObjectId;
  post: ObjectId | IPost;
  author: ObjectId | IUser;
  content: string;
  lineReference?: number;
  parentComment?: ObjectId | IComment;
  createdAt: Date;
  updatedAt: Date;
}

export type SupportedLanguage =
  | 'javascript'
  | 'typescript'
  | 'python'
  | 'go'
  | 'rust'
  | 'java'
  | 'cpp'
  | 'c'
  | 'csharp'
  | 'ruby'
  | 'php'
  | 'swift'
  | 'kotlin'
  | 'html'
  | 'css'
  | 'sql'
  | 'json'
  | 'yaml'
  | 'markdown'
  | 'shell';

export const SUPPORTED_LANGUAGES: { value: SupportedLanguage; label: string }[] = [
  { value: 'javascript', label: 'JavaScript' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'python', label: 'Python' },
  { value: 'go', label: 'Go' },
  { value: 'rust', label: 'Rust' },
  { value: 'java', label: 'Java' },
  { value: 'cpp', label: 'C++' },
  { value: 'c', label: 'C' },
  { value: 'csharp', label: 'C#' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'swift', label: 'Swift' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'sql', label: 'SQL' },
  { value: 'json', label: 'JSON' },
  { value: 'yaml', label: 'YAML' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'shell', label: 'Shell/Bash' },
];

export const CODE_SOURCES: { value: CodeSource; label: string; description: string }[] = [
  { value: 'ai', label: 'AI Generated', description: 'Code generated by an AI assistant' },
  { value: 'colleague', label: 'From Colleague', description: 'Code from a coworker or team member' },
  { value: 'personal', label: 'My Code', description: 'Code you wrote yourself' },
  { value: 'other', label: 'Other', description: 'Code from another source' },
];
